# We use conda to load the rnaseq environment and install cromwell.

language: python

python:
  - 3.6

before_install:
  - export MINICONDA=${HOME}/miniconda
  - export PATH=${MINICONDA}/bin:${PATH}
  - export CROMWELL_VERSION=0.36  # Travis does not automatically get the latest version.
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p ${MINICONDA}
  - conda config --set always_yes yes

install:
  - conda env create -n my_env -f environment.yml
  - source activate my_env
  - conda install --channel bioconda cromwell=$CROMWELL_VERSION
  - python3 -m pip install pytest-workflow

script:
  - bash-c 'python3 -m pytest -v tests/functional/test$TEST.yml'

matrix:
  include:
    - env: TEST=Rna3PairedEndVariantCalling
    - env: TEST=Rna3SingleEndVariantCalling
    - install:
        - conda install --channel bioconda cromwell=$CROMWELL_VERSION
      script:
        - for F in *.wdl; do echo $F; womtool validate $F; done
        - >
          if [ "$TRAVIS_PULL_REQUEST" != "false" ];
          then git submodule foreach --recursive bash -c
          'if [ "$(git tag --contains)" == "" ] ;
          then git checkout develop && git pull &&
          git submodule update --init --recursive ;
          else echo "on tag: $(git tag --contains)" ; fi' ;
          fi
        - >
          git diff --exit-code ||
          (echo ERROR: Git changes detected. Submodules should either be tagged or on the latest version of develop. && exit 1)
